/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;

import Visao.CadastroProdutoView;
import java.util.ArrayList;
import modelo.*;

/**
 *
 * @author marti
 */
public class SistemaVendasView extends javax.swing.JFrame {

    /**
     * Creates new form SistemaVendasView
     */
    
    private ArrayList<Categoria> categorias;
    private ArrayList<Produto> produtos;
    
    public SistemaVendasView() {
        this.categorias = new ArrayList<Categoria>();
        this.produtos = new ArrayList<Produto>();
        initComponents();
    }

    public ArrayList<Categoria> getCategorias(){
        return this.categorias;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        mbSistemaVendas = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        miCadCat = new javax.swing.JMenuItem();
        miCadPro = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        miRelCat = new javax.swing.JMenuItem();
        miRelPro = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu4.setText("jMenu4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas");

        mnCadastros.setText("Cadastros");

        miCadCat.setText("Categoria");
        miCadCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadCatActionPerformed(evt);
            }
        });
        mnCadastros.add(miCadCat);

        miCadPro.setText("Produto");
        miCadPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadProActionPerformed(evt);
            }
        });
        mnCadastros.add(miCadPro);

        mbSistemaVendas.add(mnCadastros);

        mnRelatorio.setText("Relatório");

        miRelCat.setText("Categoria");
        miRelCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelCatActionPerformed(evt);
            }
        });
        mnRelatorio.add(miRelCat);

        miRelPro.setText("Produto");
        miRelPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelProActionPerformed(evt);
            }
        });
        mnRelatorio.add(miRelPro);

        mbSistemaVendas.add(mnRelatorio);

        setJMenuBar(mbSistemaVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadCatActionPerformed
        CadastroCategoriaView cadCatV = new CadastroCategoriaView(this);
        cadCatV.setVisible(true);
    }//GEN-LAST:event_miCadCatActionPerformed

    private void miRelCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelCatActionPerformed
        RelatorioCategoriasView relCatV = new RelatorioCategoriasView(this);
        relCatV.setVisible(true);
    }//GEN-LAST:event_miRelCatActionPerformed

    private void miCadProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadProActionPerformed
        CadastroProdutoView cadProV = new CadastroProdutoView();
        cadProV.setVisible(true);
    }//GEN-LAST:event_miCadProActionPerformed

    private void miRelProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelProActionPerformed
        RelatorioProdutosView relProV = new RelatorioProdutosView();
        relProV.setVisible(true);
    }//GEN-LAST:event_miRelProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaVendasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuBar mbSistemaVendas;
    private javax.swing.JMenuItem miCadCat;
    private javax.swing.JMenuItem miCadPro;
    private javax.swing.JMenuItem miRelCat;
    private javax.swing.JMenuItem miRelPro;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnRelatorio;
    // End of variables declaration//GEN-END:variables

    Object getCategorias() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    Iterable<Categoria> getCategorias() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
